CREATE TABLE IF NOT EXISTS  PUBLIC.USERS_TABLE (
	USERID BIGINT NOT NULL AUTO_INCREMENT,
	EMAIL VARCHAR(150) NOT NULL,
	FIRSTNAME VARCHAR(200) NOT NULL,
	MIDDLENAME VARCHAR(200) DEFAULT '',
	LASTNAME VARCHAR(200) NOT NULL,
        PASSWORD VARCHAR(500) NOT NULL,
        WROLE VARCHAR(10) NOT NULL,
	CONSTRAINT USERS_TABLE_PK PRIMARY KEY (USERID),
        CONSTRAINT USERS_TABLE_UN UNIQUE KEY (EMAIL)
)
